# Generated by Django 2.2.5 on 2019-09-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorappConfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='tarifa_hora',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='descripcion_perfil',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estudios',
            field=models.ManyToManyField(blank=True, to='asesorappConfig.Estudio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='url_foto',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
