# Generated by Django 2.2.5 on 2019-09-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asesorappConfig', '0002_auto_20190928_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='caso',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='asesorappConfig.Caso'),
        ),
    ]
